### ISSUE TITLE
how to use AES256 instead of AES 128

### ISSUE THREAD

**Issue by hishamBakr** [scottyab/secure-preferences#17]
Thank you for the great library. I suggested using this library in our project but security team gave me this comment. Please advise.

For local storage of the user passwords use at least AES 256 minimum not 128.
When using  PKCS5, verify that the implementation does not allow for Oracle padding attacks in that the responding side does not leak padding validation to the client. See the following
https://www.owasp.org/images/e/eb/Fun_with_Padding_Oracles.pdf
 
Make sure that the stored credentials are place under the /data/data path on Android and not in user land on the sd card.
On uninstallation of the application, all user data including the stored encrypted credentials should be deleted.
 
How is the key and key password protected?
 Preferably  obfuscate the mechanism to create the key and password  in native .so files if this is viable.
 
Do not have the key and key password present in plaintext in the Java source code.

Use a  method to generate the key and password and then obfuscate this method with proguard.
Proguard should also be used to hide  any inputs into this method.

Ideally use a per user key and  password, this can be created based off of the android device id.

**Comment by scottyab** [comment]
Thanks for your/security teams comments... that list sound more of a generic check list rather than specific to this lib? (i may of misunderstood)
 
I felt generally 128 is as strong enough it's just generally people tend to 'require' maybe without understanding the differences/benefits, here's a good [blog](https://blog.agilebits.com/2013/03/09/guess-why-were-moving-to-256-bit-aes-keys/) about it. Of course this and the [core](https://github.com/scottyab/java-aes-crypto) are an open source lib please do fork and PR change to AES 256 if you'd like. 

That said rather than store the user password if you can request off the user each time the app is opened and use [this constructor](https://github.com/scottyab/secure-preferences/blob/master/library/src/main/java/com/securepreferences/SecurePreferences.java#L125) the  user password this is never stored. 

The shared prefers are not stored on SDcard (this is an Android thing not something this lib does) additionally using via this lib can only be opened context private. 

You can implement ProGuard or ideally something stronger like DexGuard's class encryption. 

The if you use the password described above the key is derived from the password, if not then yes, yeah each key is derived per device.

**Comment by hishamBakr** [comment]
Thank you very much for your reply :)
